site:
    title: Website Title
    description: hola!
    author: Anonymous
    pretty_urls: false
    blogs: [ post, concerten ]
    analytics: UA-26048593-1
    twitter_handle: jqno
    twitter_follow: true
    
smartypants:
    enable: true

baker:
    skip_patterns:
        - /^index.php/
    config_variants:
        default:
            site:
                root: http://www.jqno.nl

