site:
    title: Website Title
    description: hola!
    author: Anonymous
    pretty_urls: false
    blogs: [ post, concerten ]
    twitter_handle: jqno
    twitter_follow: true
    
smartypants:
    enable: true

baker:
    skip_patterns:
        - /^index.php/

