site:
    title: Website Title
    description: hola!
    author: Anonymous
    pretty_urls: true
    blogs: [ post, concerts ]
    tag_url: tags/%tag%
    category_url: at/%category%
    analytics: UA-26048593-1
    twitter_handle: jqno
    twitter_follow: true

post:
    feed_url: http://feeds.feedburner.com/trouwens

smartypants:
    enable: true

baker:
    skip_patterns:
        - /^index.php/
    config_variants:
        default:
            site:
                root: http://www.jqno.nl

