site:
    title: tr ouwens
    description: by the way: things I want to say
    meta_description: This is my blog on software development and (sometimes) other things.
    author: Jan Ouwens
    pretty_urls: true
    posts_per_page: 0
    blogs: [ post, equalsverifier, concerts ]
    tag_url: tags/%tag%
    category_url: at/%category%
    analytics: UA-26048593-1
    disqus_root: http://www.jqno.nl/
    twitter_handle: jqno
    twitter_follow: true
    auto_formats:
        md: markdown

blogs:
    post:
        tagcloud_lower: 2
        tagcloud_upper: 5
        feed_url: http://feeds.feedburner.com/trouwens

    concerts:
        tagcloud_lower: 2
        tagcloud_upper: 5
        catcloud_lower: 2
        catcloud_upper: 5

    equalsverifier:
        title: equals verifier
        description: testing equals and hashCode
        analytics: UA-10447367-2
        feed_url: http://feeds.feedburner.com/trouwens

smartypants:
    enable: true

baker:
    skip_patterns:
        - /^index.php/
    config_variants:
        default:
            site:
                root: http://www.jqno.nl

